using Asp.Versioning;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Ai.Prompt.Core.Prompts;
using Umbraco.Ai.Prompt.Web.Api.Management.Prompt.Models;

namespace Umbraco.Ai.Prompt.Web.Api.Management.Prompt.Controllers;

/// <summary>
/// Controller for creating prompts.
/// </summary>
[ApiVersion("1.0")]
public class CreatePromptController : PromptControllerBase
{
    private readonly IAiPromptService _aiPromptService;

    /// <summary>
    /// Creates a new instance of the controller.
    /// </summary>
    public CreatePromptController(IAiPromptService aiPromptService)
    {
        _aiPromptService = aiPromptService;
    }

    /// <summary>
    /// Creates a new prompt.
    /// </summary>
    /// <param name="model">The prompt creation request.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The created prompt.</returns>
    [HttpPost]
    [MapToApiVersion("1.0")]
    [ProducesResponseType(typeof(PromptResponseModel), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> CreatePrompt(
        [FromBody] CreatePromptRequestModel model,
        CancellationToken cancellationToken = default)
    {
        var now = DateTime.UtcNow;
        var prompt = new AiPrompt
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = model.Alias,
            Name = model.Name,
            Content = model.Content,
            Description = model.Description,
            ProfileId = model.ProfileId,
            Tags = model.Tags?.ToList() ?? [],
            IsActive = true,
            DateCreated = now,
            DateModified = now
        };

        try
        {
            var created = await _aiPromptService.SavePromptAsync(prompt, cancellationToken);

            return CreatedAtAction(
                nameof(ByIdOrAliasPromptController.GetPromptByIdOrAlias),
                "ByIdOrAliasPrompt",
                new { promptIdOrAlias = created.Id },
                created.Id.ToString());
        }
        catch (InvalidOperationException ex) when (ex.Message.Contains("already exists"))
        {
            return AliasAlreadyExists(model.Alias);
        }
    }
}
